### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by archonic** [contently/daisydiff#3]
Happy to see a ruby wrapper for DaisyDiff :tada:

Could we get some usage instructions in the readme?

**Comment by sanjayginde** [comment]
@archonic I missed this issue, as I didn't think anybody was using this! If you're using it, mind sending a PR with instructions?

Though, I'd recommend looking to move to our service implementation instead @ https://github.com/contently/html-diff-service. We built it to remove the Java dependency from our Rails application.

**Comment by archonic** [comment]
Good to know there's a service gem. I ended up wrapping a python library and making a gem out of that here: https://github.com/archonic/ruby_html_tree_differ. If I have problems with that, I'll give html-diff-service a shot. Thanks!
